### PR TITLE
refactor & upgrade to support gdc dictionary

### PR DESCRIPTION
**Pull request by ganjigajanan**
- Selective nodes export & import
- Add support for complex link export & import
- Add support for dynamic export/ import all the properties, current script is meant to export only specific properties - hardcoded structure
- References (at all levels except the link references) to be a list rather than string & normalize to $ref
- Add support for enumDef & deprecated enums ( leads to moving enums to separate tsv on its own)
- If a property supports more than one type - convert it to "oneOf" clause
- Add support for project, program, root, data_release yamls
- Add support for terms file export & import
- Add placeholder rows for new terms references added in the main yaml to be added to terms files export & import

### CODE REVIEW

**Review by wwysoc2 — APPROVED** [review]
Cool, I'll be happy to go through this in depth some other time, but if this is what you've been using for Thidwick, I approve this PR

**Comment by mysterious-progression** [comment]
Nice upgrades! I'm not current on the latest Gen3 schema. Are we still using `enumTerms`? It appears this format is not supported in this update. Also, should we be using .tsv instead of .txt files so that vendors don't have to make this conversion?
Lastly, it looks like enum values `NA` get converted to ' ' like in this case from the Blood Pac dictionary `hi_si_risk_assessment` node
```
  actions3:
    description: VA contact names and numbers provided
    enum:
      - I don't know
      - NA
      - "No"
      - "Yes"
```
gets converted to 
```
 actions3:
    description: >-
      VA contact names and numbers provided
    enum:
      - I don't know
      - ''
      - "No"
      - "Yes"
```

Chris?

**Review by cgmeyer — COMMENTED** [review]
We should be able to allow both TXT and TSV input formats, and just treat them as tab separated. I prefer the output files to be TSV format.
WRT enum terms, I'm not sure if our bioinfos (LaRon) are actively/manually adding them to data dictionaries? If so, we don't want them to disappear when they run this tool. That being said, I don't think the data portal supports them yet.  So, whether we support it in this tool at this time depends on if our data dictionary creators need to retain that information in the yamls (I for one don't ever add enum terms, and I think it's only LaRon who does, but we should check with the User Services/Bioinformatics Teams.)

WRT "NA" in an enums list, yes, we should make sure they get treated as strings ("NA", not null or NaN, etc.).

**Comment by ganjigajanan** [comment]
good observations @mattreex , see below responses:
1. `enumTerms` is nothing but `enumDef` which along with deprecated enums made us to move the enums to separate tsv. if it needs to be referred as `enumTerms` it just needs `enumDef` to be replaced by `enumTerms`. we have decided to name the column as `enumDef` to keep it consistent with `termDef` in the `_terms.yaml`. I removed the dependency of it population based on a flag provided by user as it will be populated only if the column has any values in it, under the given property section. otherwise it will not put the section in the yaml file.
2. Earlier it was indeed using `.tsv` instead of `.txt` and these files were opened in MS Excel to work with them & update. while saving the files as tab delimited files it uses `.txt` extension. after saving those need to renamed to change the extension to `.tsv` for them to be picked up by script, which is an additional step. to reduce that extra step, the extension was changed to `.txt`. @cgmeyer  hope that is ok. if you still like to have a support for `.tsv` we can add additional flag with which user can mention the extension they want to save & to read in both yaml2tsv & tsv2yaml. 
3. thats a nice catch! i think 'NA' is getting evaluated to '' through yaml read, I've updated that.

**Comment by ganjigajanan** [comment]
@mattreex please check if this version has fixed NA to '' issue, once you confirm it fixed, I'll merge the branch into master.

**Comment by mattreex** [comment]
It looks like it still outputs ' ' instead of NA. Regarding enumTerms, there was a distinct syntactical  difference between enumTerms and enumDef when this tool was developed. Specifically, 
enumTerms follows 
```
terms:
 -$ref: "_terms.yaml#/C159691"
 -$ref: "_terms.yaml#/C25213"
 -$ref: "_terms.yaml#/C14215"
enumTerms:
 HBV positive:
   -$ref: "_terms.yaml#/C141405
```
For each property, and enumDef follows
```
 term:
      $ref: "_terms.yaml#/gender"
    enum:
      - female
      - male
      - unknown
      - unspecified
      - not reported
    termDef:
      - term: Gender
        source: NCI Thesaurus
        term_id: C17357
        term_version: 18.11d (Release date:2018-11-26)
    enumDef:
      - enumeration: Female
        source: NCI Thesaurus
        term_id: C46110
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Male
        source: NCI Thesaurus
        term_id: C84364
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Unknown
        source: NCI Thesaurus
        term_id: C17998
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Unspecified
        source: NCI Thesaurus
        term_id: C38046
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Not Reported
        source: NCI Thesaurus
        term_id:  C43234
        term_version: 18.09d (Release date:2018-09-24)
```
I am also not able to convert the NIAID dictionary to tsvs
```
Traceback (most recent call last):
  File "yaml2tsv.py", line 777, in <module>
    export_nodes_props(yamdics, out_dir, dictionary)
  File "yaml2tsv.py", line 437, in export_nodes_props
    val_dict, enum_dict = get_var_values(dic, val_dict, enum_dict)
  File "yaml2tsv.py", line 262, in get_var_values
    for k, v in enum_def.items():
AttributeError: 'list' object has no attribute 'items'
```

**Review by mysterious-progression — COMMENTED** [review]
It looks like it still outputs ' ' instead of NA. Regarding enumTerms, there was a distinct syntactical difference between enumTerms and enumDef when this tool was developed. Specifically,
enumTerms follows
```
terms:
 -$ref: "_terms.yaml#/C159691"
 -$ref: "_terms.yaml#/C25213"
 -$ref: "_terms.yaml#/C14215"
enumTerms:
 HBV positive:
   -$ref: "_terms.yaml#/C141405
```
For each property, and enumDef follows
```
 term:
      $ref: "_terms.yaml#/gender"
    enum:
      - female
      - male
      - unknown
      - unspecified
      - not reported
    termDef:
      - term: Gender
        source: NCI Thesaurus
        term_id: C17357
        term_version: 18.11d (Release date:2018-11-26)
    enumDef:
      - enumeration: Female
        source: NCI Thesaurus
        term_id: C46110
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Male
        source: NCI Thesaurus
        term_id: C84364
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Unknown
        source: NCI Thesaurus
        term_id: C17998
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Unspecified
        source: NCI Thesaurus
        term_id: C38046
        term_version: 18.09d (Release date:2018-09-24)
      - enumeration: Not Reported
        source: NCI Thesaurus
        term_id:  C43234
        term_version: 18.09d (Release date:2018-09-24)
```
I am also not able to convert the NIAID dictionary to tsvs
```
Traceback (most recent call last):
  File "yaml2tsv.py", line 777, in <module>
    export_nodes_props(yamdics, out_dir, dictionary)
  File "yaml2tsv.py", line 437, in export_nodes_props
    val_dict, enum_dict = get_var_values(dic, val_dict, enum_dict)
  File "yaml2tsv.py", line 262, in get_var_values
    for k, v in enum_def.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by ganjigajanan** [comment]
@mattreex I have updated the code to handle NA. Pandas was converting it to `NaN` while reading the TSVs. For NIAID the dictionary you were testing was a legacy dictionary which is obsolete now. use following dictionaries to test.
https://github.com/uc-cdis/TB_datadictionary
https://github.com/uc-cdis/Charlie_datadictionary
https://github.com/uc-cdis/Flu_datadictionary
https://github.com/uc-cdis/Microbiome_datadictionary

As NA converting to '' is fixed, I'll merge this branch into master & create a release. all the other changes & improvements will be done as a next phase/version of the tool.

**Comment by ganjigajanan** [comment]
@mattreex I have updated the code to handle NA. Pandas was converting it to `NaN` while reading the TSVs. For NIAID the dictionary you were testing was a legacy dictionary which is obsolete now. use following dictionaries to test.
https://github.com/uc-cdis/TB_datadictionary
https://github.com/uc-cdis/Charlie_datadictionary
https://github.com/uc-cdis/Flu_datadictionary
https://github.com/uc-cdis/Microbiome_datadictionary

As NA converting to '' is fixed, I'll merge this branch into master & create a release. all the other changes & improvements will be done as a next phase/version of the tool.

**Comment by mysterious-progression** [comment]
Thanks for the update! I am receiving the same issue with the Charlie data dictionary as I did with the ndh data dictionary. 

```
Traceback (most recent call last):
  File "yaml2tsv.py", line 777, in <module>
    export_nodes_props(yamdics, out_dir, dictionary)
  File "yaml2tsv.py", line 437, in export_nodes_props
    val_dict, enum_dict = get_var_values(dic, val_dict, enum_dict)
  File "yaml2tsv.py", line 262, in get_var_values
    for k, v in enum_def.items():
AttributeError: 'list' object has no attribute 'items'
```
At the moment, I don't actually see a difference in the between ndh schemas and Charlie schemas.
I think the error is being generated when attempting to retrieve enums from the enumDef syntax

**Pull request merged**
